# Generated by Django 5.1.1 on 2024-10-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_register', '0004_remove_myuser_department_remove_myuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
