# Generated by Django 5.1.1 on 2024-10-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_register', '0005_myuser_department_myuser_gender_myuser_name_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission'),
        ),
    ]
