# Generated by Django 5.1.1 on 2024-10-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_register', '0009_alter_myuser_email_alter_myuser_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='student_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
